#!/bin/bash

# Credits: https://github.com/alrra/dotfiles
# ----------------------------------------------------------------------
# | Prompts                                                            |
# ----------------------------------------------------------------------

get_git_repository_details() {

    local branchName=''
    local tmp=''

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check if the current directory is in a Git repository
    [ "$(git rev-parse &>/dev/null; printf $?)" -ne 0 ] && return

    # Check if in `.git/` directory (some of the following
    # checks don't make sense/won't work in the `.git` directory)
    [ "$(git rev-parse --is-inside-git-dir)" == "true" ] && return

    # Check for uncommitted changes in the index
    if ! $(git diff --quiet --ignore-submodules --cached); then
        tmp="$tmp+";
    fi

    # Check for unstaged changes
    if ! $(git diff-files --quiet --ignore-submodules --); then
        tmp="$tmp!";
    fi

    # Check for untracked files
    if [ -n "$(git ls-files --others --exclude-standard)" ]; then
        tmp="$tmp?";
    fi

    # Check for stashed files
    if $(git rev-parse --verify refs/stash &>/dev/null); then
        tmp="$tmp$";
    fi

    [ -n "$tmp" ] && tmp=" [$tmp]"


    branchName="$( printf "$( git rev-parse --abbrev-ref HEAD 2> /dev/null \
        || git rev-parse --short HEAD 2> /dev/null \
        || printf " (unknown)" )" | tr -d "\n" )"


    printf "%s" "$1$branchName$tmp"

}

set_prompts() {

    local black='' blue='' bold='' cyan='' green='' orange='' \
          purple='' red='' reset='' white='' yellow=''

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    bold=''
    reset="\e[0m"
    
    light_blue="\e[1;94m"
    gray="\e[1;90m"
    black="\e[1;30m"
    blue="\e[1;34m"
    cyan="\e[1;36m"
    green="\e[1;32m"
    orange="\e[1;33m"
    purple="\e[1;35m"
    red="\e[1;31m"
    white="\e[1;37m"
    yellow="\e[1;33m"


    PS1="\[\033]0;\w\007\]"         # Terminal title (set to the
                                    # current working directory)
    PS1+="\[$bold\]"
    PS1+="\[$gray\]\u"            # Username
    # PS1+="\[$white\]@"
    # PS1+="\[$blue\]\h"            # Host
    PS1+="\[$white\]: "
    PS1+="\[$green\]\w"             # Working directory
    PS1+="\$(get_git_repository_details \"$white on $cyan\")"
    PS1+="\n"
    PS1+="\[$reset$white\]\$ \[$reset\]"

    export PS1

    PS2='⚡ '

    export PS2

    PS4="+$( tput cr && tput cuf 6 && printf "%s $reset" )"

    export PS4

}

# ----------------------------------------------------------------------
# | Main                                                               |
# ----------------------------------------------------------------------

main() {
    set_prompts
}

main

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Unset anything that just pollutes the global space

unset -f main
unset -f set_prompts
